interface eth0
 ip address 172.16.0.1/30

interface eth1
 ip address 172.16.0.5/30

interface eth2
 ip address 172.16.0.9/30

interface lo
 ip address 10.255.0.1/32

router ospf
 ospf router-id 10.255.0.1

 network 172.16.0.0/30 area 0
 network 172.16.0.4/30 area 0
 network 172.16.0.8/30 area 0

 network 10.255.0.1/32 area 0

router bgp 65000
 bgp router-id 10.255.0.1
 no bgp default ipv4-unicast

 neighbor 10.255.0.11 remote-as 65000
 neighbor 10.255.0.12 remote-as 65000
 neighbor 10.255.0.13 remote-as 65000

 neighbor 10.255.0.11 update-source lo
 neighbor 10.255.0.12 update-source lo
 neighbor 10.255.0.13 update-source lo

 neighbor 10.255.0.11 route-reflector-client
 neighbor 10.255.0.12 route-reflector-client
 neighbor 10.255.0.13 route-reflector-client

 address-family l2vpn evpn
  neighbor 10.255.0.11 activate
  neighbor 10.255.0.12 activate
  neighbor 10.255.0.13 activate

 exit-address-family